# Generated by Django 5.0.1 on 2025-12-12 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_userprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The question text')),
                ('answer', models.TextField(help_text='The answer text')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(help_text='The lesson this FAQ belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Lesson FAQ',
                'verbose_name_plural': 'Lesson FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The question text')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(help_text='The lesson this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The choice text', max_length=200)),
                ('is_correct', models.BooleanField(default=False, help_text='Is this the correct answer?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
                ('question', models.ForeignKey(help_text='The question this choice belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='lessons.question')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
                'ordering': ['order'],
            },
        ),
    ]
